spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username : root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    # Activiti数据库表处理策略，第一次true建表，create-drop启动建表关闭删表
    database-schema-update: false
    db-history-used: true
    history-level: full
    # # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: true
    # async-executor-activate: true
    # ActivitiProperties.java中配置了prefix = "classpath*:**/processes/"
    # process-definition-location-prefix: classpath:/
  security:
    user:
      name: admin
      password: admin
